package infringements

type Infringement uint8

const (
	Blocking_by_slow_driving Infringement = iota
	Blocking_by_wrong_way_driving
	Reversing_off_the_start_line
	Big_Collision
	Small_Collision
	Collision_failed_to_hand_back_position_single
	Collision_failed_to_hand_back_position_multiple
	Corner_cutting_gained_time
	Corner_cutting_overtake_single
	Corner_cutting_overtake_multiple
	Crossed_pit_exit_lane
	Ignoring_blue_flags
	Ignoring_yellow_flags
	Ignoring_drive_through
	Too_many_drive_throughs
	Drive_through_reminder_serve_within_n_laps
	Drive_through_reminder_serve_this_lap
	Pit_lane_speeding
	Parked_for_too_long
	Ignoring_tyre_regulations
	Too_many_penalties
	Multiple_warnings
	Approaching_disqualification
	Tyre_regulations_select_single
	Tyre_regulations_select_multiple
	Lap_invalidated_corner_cutting
	Lap_invalidated_running_wide
	Corner_cutting_ran_wide_gained_time_minor
	Corner_cutting_ran_wide_gained_time_significant
	Corner_cutting_ran_wide_gained_time_extreme
	Lap_invalidated_wall_riding
	Lap_invalidated_flashback_used
	Lap_invalidated_reset_to_track
	Blocking_the_pitlane
	Jump_start
	Safety_car_to_car_collision
	Safety_car_illegal_overtake
	Safety_car_exceeding_allowed_pace
	Virtual_safety_car_exceeding_allowed_pace
	Formation_lap_below_allowed_speed
	Retired_mechanical_failure
	Retired_terminally_damaged
	Safety_car_falling_too_far_back
	Black_flag_timer_infringement
	Unserved_stop_go_penalty
	Unserved_drive_through_penalty
	Engine_component_change
	Gearbox_change
	League_grid_penalty
	Retry_penalty
	Illegal_time_gain
	Mandatory_pitstop
)
