package driver

//DRIVERS
type Driver uint8

const (
	Carlos_Sainz Driver = iota
	Daniil_Kvyat
	Daniel_Ricciardo
	Fernando_Alonso
	Felipe_Massa
	Kimi_Räikkönen
	Lewis_Hamilton
	Max_Verstappen
	Nico_Hulkenburg
	Kevin_Magnussen
	Romain_Grosjean
	Sebastian_Vettel
	Sergio_Perez
	Valtteri_Bottas
	Esteban_Ocon
	Lance_Stroll
	Arron_Barnes
	Martin_Giles
	Alex_Murray
	Lucas_Roth
	Igor_Correia
	Sophie_Levasseur
	Jonas_Schiffer
	Alain_Forest
	Jay_Letourneau
	Esto_Saari
	Yasar_Atiyeh
	Callisto_Calabresi
	Naota_Izum
	Howard_Clarke
	Wilheim_Kaufmann
	Marie_Laursen
	Flavio_Nieves
	Peter_Belousov
	Klimek_Michalski
	Santiago_Moreno
	Benjamin_Coppens
	Noah_Visser
	Gert_Waldmuller
	Julian_Quesada
	Daniel_Jones
	Artem_Markelov
	Tadasuke_Makino
	Sean_Gelael
	Nyck_De_Vries
	Jack_Aitken
	George_Russell
	Maximilian_Günther
	Nirei_Fukuzumi
	Luca_Ghiotto
	Lando_Norris
	Sérgio_Sette_Câmara
	Louis_Delétraz
	Antonio_Fuoco
	Charles_Leclerc
	Pierre_Gasly
	Alexander_Albon
	Nicholas_Latifi
	Dorian_Boccolacci
	Niko_Kari
	Roberto_Merhi
	Arjun_Maini
	Alessio_Lorandi
	Ruben_Meijer
	Rashid_Nair
	Jack_Tremblay
	Devon_Butler
	Lukas_Weber
	Antonio_Giovinazzi
	Robert_Kubica
	Alain_Prost
	Ayrton_Senna
	Nobuharu_Matsushita
	Nikita_Mazepin
	Guanya_Zhou
	Mick_Schumacher
	Callum_Ilott
	Juan_Manuel_Correa
	Jordan_King
	Mahaveer_Raghunathan
	Tatiana_Calderon
	Anthoine_Hubert
	Guiliano_Alesi
	Ralph_Boschung
	Michael_Schumacher
	Dan_Ticktum
	Marcus_Armstrong
	Christian_Lundgaard
	Yuki_Tsunoda
	Jehan_Daruvala
	Gulherme_Samaia
	Pedro_Piquet
	Felipe_Drugovich
	Robert_Schwartzman
	Roy_Nissany
	Marino_Sato
	Aidan_Jackson
	Casper_Akkerman
	Jenson_Button
	David_Coulthard
	Nico_Rosberg
)
